export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_REPOS = 'GET_USER_REPOS';
export const RESET_USER_DATA = 'RESET_USER_DATA';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';